title: rock-paper-scissors-by-hand
hero_image: images/banner.png
description: rock-paper-scissors-by-hand description
version: 4
listed: false
copyedit: false
last_tested: "2020-12-02"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
