---
title: Rock, paper, scissors by hand
hero_image: images/banner.png
description: Use Google's Teachable Machine to build a rock, paper, scissors game
  controlled by hand gestures
version: 4
listed: true
copyedit: true
last_tested: '2020-06-12'
steps:
- title: Introduction
- title: Get started with Teachable Machine
- title: Collect your training data
  completion:
  - engaged
- title: Create your model
- title: Set up your game
  completion:
  - internal
- title: Connect your model to the game
  completion:
  - external
